### ISSUE TITLE
Would you mind considering our arxiv paper: "Unsupervised Universal Self-Attention Network for Graph Classification"

### ISSUE THREAD

**Issue by daiquocnguyen** [jdlc105/Must-read-papers-and-continuous-tracking-on-Graph-Neural-Network-GNN-progress#4]
Thank you very much for your work. It's very great.

We have a paper titled "[Unsupervised Universal Self-Attention Network for Graph Classification](https://arxiv.org/pdf/1909.11855.pdf)" which, to the best of our knowledge, is the first consideration of using the unsupervised training setting to train a GNN-based model for the graph classification task. We show that a unsupervised model can noticeably outperform up-to-date supervised models by a large margin. [The code](https://github.com/daiquocnguyen/U2GNN) is also available to reproduce the experimental results.

Would you mind adding it to your list? Thank you very much.

**Comment by jdlc105** [comment]
Hi,

Thanks for your appreciation and supporting on our project! Sorry we have been too busy lately to reply in time. Your paper looks very novel. In order to maintain and improve the quality of our project, we will carefully and quickly review your paper mainly from two perspective of important theoretical contribution and novel application scenario. If it meets the requirements, we will add your paper to our repository soon.

Friendly yours.
Allen Bluce and Anne Bluce

**Comment by daiquocnguyen** [comment]
Thank you for your consideration.

With best regards,
Dai.
