### ISSUE TITLE
GraphSAINT paper from ICLR 2020

### ISSUE THREAD

**Issue by ZimpleX** [jdlc105/Must-read-papers-and-continuous-tracking-on-Graph-Neural-Network-GNN-progress#5]
Hi, 

Thanks for the great collection! I think it may be appropriate to add this paper from ICLR 2020 to your repo as well:

GraphSAINT: Graph sampling based inductive learning approach. 

It proposes a new minibatch sampling algorithm that improves the accuracy as well as training time on large graphs and deep models. The minibatch algorithm has also been tested on a variety of GNN architectures (e.g., GraphSAGE, GAT, JK-net) as well. 

Thanks

**Comment by jdlc105** [comment]
Hello,

Thanks for your appreciation and supporting on our project!  Sorry we have been too busy lately to reply in time.  Your paper looks very good. In order to maintain and improve the quality of our project, we will carefully and quickly review your paper mainly from two perspective of important theoretical contribution and novel application scenario. If it meets the requirements, we will add your paper to our repository soon.

Friendly yours.
Allen Bluce and Anne Bluce

**Comment by ZimpleX** [comment]
Thanks for your reply! Looking forward to hearing from you. 

FYI, source code:
github.com/GraphSAINT/GraphSAINT
